name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          sudo docker run --net host -i -v .:/root/ovutil -w /root/ovutil ubuntu:22.04 /bin/bash -c 'apt update && apt install -y cmake ninja-build clang clang-format lld && bash -x build.bash --arch x86_64 --debug'
