name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build clang clang-format lld
      - name: Build
        run: |
          mkdir -p build/ovbase build/ovutil
          cd build
          rm -rf ovbase/CmakeCache.txt && cmake -S ../3rd/ovbase -B ovbase --preset default -DFORMAT_SOURCES=OFF -DCMAKE_INSTALL_PREFIX=local
          cmake --build ovbase && ctest --test-dir ovbase --output-on-failure --output-junit testlog.xml
          
          rm -rf ovutil/CmakeCache.txt && cmake -S .. -B ovutil --preset default -DOVBASE_PATH=$(pwd)/ovbase -DFORMAT_SOURCES=OFF -DCMAKE_INSTALL_PREFIX=local
          cmake --build ovutil && ctest --test-dir ovutil --output-on-failure --output-junit testlog.xml
